In [4]:
import numpy as np
import tensorflow as tf
import tensorflow.keras as keras
tf.keras.backend.set_floatx('float64')

In [8]:
dim1 = 300
dim2 = 2
x_tf = tf.random.normal([1000,dim1],dtype ='float64')
x = x_tf.numpy()
inputs = keras.Input(shape=(dim1))
l = tf.keras.layers.Dense(units = dim2, activation='linear')
outputs = l(inputs)
model = tf.keras.Model(inputs = inputs, outputs = outputs)
w,b = model.get_weights()
print(model.call(x_tf) - model(x_tf))
print(model(x_tf) - model(x))
print(model(x) - x_tf@w + b)
print(model(x) - (x@w + b))
print(model.predict(x) - (x@w + b))

tf.Tensor(
[[0. 0.]
 [0. 0.]
 [0. 0.]
 ...
 [0. 0.]
 [0. 0.]
 [0. 0.]], shape=(1000, 2), dtype=float64)
tf.Tensor(
[[0. 0.]
 [0. 0.]
 [0. 0.]
 ...
 [0. 0.]
 [0. 0.]
 [0. 0.]], shape=(1000, 2), dtype=float64)
tf.Tensor(
[[0. 0.]
 [0. 0.]
 [0. 0.]
 ...
 [0. 0.]
 [0. 0.]
 [0. 0.]], shape=(1000, 2), dtype=float64)
tf.Tensor(
[[ 8.88178420e-16  1.11022302e-15]
 [ 4.44089210e-16 -4.99600361e-16]
 [ 0.00000000e+00  4.44089210e-16]
 ...
 [-1.11022302e-16 -6.66133815e-16]
 [-8.88178420e-16  3.33066907e-16]
 [ 0.00000000e+00  0.00000000e+00]], shape=(1000, 2), dtype=float64)
[[-4.44089210e-16  1.11022302e-15]
 [ 4.44089210e-16 -5.93275429e-16]
 [-1.77635684e-15  0.00000000e+00]
 ...
 [ 8.88178420e-16 -1.11022302e-15]
 [-2.22044605e-15  1.11022302e-16]
 [-2.22044605e-16  2.22044605e-16]]


In [1]:
import numpy as np
import tensorflow as tf
a_tf = tf.random.normal([1000,300],dtype = 'float64')
a = a_tf.numpy()
b_tf = tf.random.normal([300,2],dtype = 'float64')
b = b_tf.numpy()
c_tf = tf.linalg.matmul(a_tf,b_tf)
c = np.matmul(a,b)
print(c_tf.numpy() - c)

[[ 1.50990331e-14 -9.32587341e-15]
 [ 0.00000000e+00 -1.77635684e-15]
 [-5.32907052e-15  8.88178420e-16]
 ...
 [ 0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00 -3.55271368e-15]
 [-6.21724894e-15 -1.77635684e-15]]
